blog/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include("index.urls")),
]

index/urls.py
from django.urls import path, re_path
from index import views


app_name="blog"

urlpatterns = [
    path('index/', views.index, name="index"),
    re_path('detail/(?P<art_id>[0-9]+)', views.article_content, name="detail"),
    re_path('edit/(?P<art_id>[0-9]+)',views.article_edit,name="edit"),
    path('edit_action/',views.edit_action,name="edit_action"),
    re_path('mydelete/(?P<art_id>[0-9]+)',views.mydelete, name="mydelete")


]

index/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32,default='title')
    content = models.TextField(null=True,blank=True)
    pub_time = models.DateTimeField(auto_now=True)
    author = models.TextField(null=True,blank=True)
    art_class = models.CharField(max_length=32,default='null')

    def __str__(self):
        return self.title

index/views.py
from django.shortcuts import render
from .models import Article
# Create your views here.

def index(request):
    articles=Article.objects.all()
    return render(request,"index.html",{'articles':articles})

def  article_content(request,art_id):
    article=Article.objects.get(pk=art_id)
    return render(request,"content.html",{'art':article})

def mydelete(request,art_id):
    article=Article.objects.get(pk=art_id)
    article.delete()
    return render(request,"delete.html")



def article_edit(request,art_id):
    if str(art_id)=='0':
        return render(request,"edit.html")
    else:
        art=Article.objects.get(pk=art_id)
        return render(request, "edit.html",{'art':art})

def edit_action(request):
    title=request.POST.get("title","DEFAULT")
    content = request.POST.get("content","DEFAULT")
    pub_time = request.POST.get("pub_time","DEFAULT")
    author = request.POST.get("author","DEFAULT")
    art_class = request.POST.get("art_class", "DEFAULT")
    art_id=request.POST.get("art_id","0")
    if art_id=='0':
        Article.objects.create(title=title,content=content,pub_time=pub_time,author=author,art_class=art_class)
        arts=Article.objects.all()
        return render(request,"index.html",{'articles':arts})
    else:
        article=Article.objects.get(pk=art_id)
        article.title=title
        article.content=content
        article.pub_time=pub_time
        article.author=author
        article.art_class=art_class
        article.save()
        article=Article.objects.get(pk=art_id)
        return render(request,"content.html",{"art":article})


# Create your views here.

templates/content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章详情页</title>
</head>
<body>

    <h1>{{ art.title }}</h1>
    <h2>{{ art.content}}</h2>
    <h2>{{ art.pub_time }}</h2>
    <h2>{{ art.author }}</h2>
    <h2>{{ art.art_class }}</h2>
    <br>
    <br>
    <br>
    <a href="{% url 'blog:edit' art.id %}"><h1>修改文章</h1></a>
    <a href="{% url 'blog:index' %}"><h2>返回主页</h2></a>
    <a href="{% url 'blog:mydelete' art.id %}"><h1>删除文章</h1></a>

</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>删除操作</title>
</head>
<body>

        <h2>删除成功</h2>
        <a href="{% url 'blog:index' %}"><h2>返回主页</h2></a>


</body>
</html>

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发布新文章页面</title>
</head>
<body>
    <form action="{% url "blog:edit_action" %}" method="post" >
        {% csrf_token %}

        <label><h3>文章标题：</h3></label>
        <input type="text" name="title" {% if art %}value="{{ art.title }}{% endif %}">
        <br>
        <br>
        <br>
        <label><h3>文章内容 ：</h3></label>
        <input type="text" name="content" {% if art %}value="{{ art.content }}{% endif %}">
        <br>
        <br>
        <br>
        <label><h3>作者 ：</h3></label>
        <input type="text" name="author" {% if art %}value="{{ art.author }}{% endif %}">
        <br>
        <br>
        <br>
        <label><h3>类别 ：</h3></label>
        <input type="text" name="art_class" {% if art %}value="{{ art.art_class }}{% endif %}">

        <input type="hidden" value="{{ art.id | default:'0'}}" name="art_id">
        <br>
        <br>
        <br>
        <input type="submit" value="提交保存">

    </form>
    <a href="{% url 'blog:index' %}"><h2>返回主页</h2></a>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎来到我的博客页面</title>
</head>
<body>
    <h1>博客文章列表如下：</h1>
    <br>
    <br>
    {% for art in articles %}
        <a style="text-decoration: none" href="{% url 'blog:detail' art.id %}"><h2>{{ forloop.counter }}    {{ art.title }}</h2></a>
    {% endfor %}
    <br>
    <br>
    <br>
    <a href="{% url 'blog:edit' 0 %}"><h1>发布新文章</h1></a>

</body>
</html>